apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  install:
    remediation:
      retries: -1
  interval: 5m
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: cert-manager
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.18.1
  values:
    cainjector:
      enabled: true
    featureGates: ACMEHTTP01IngressPathTypeExact=false
    installCRDs: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     email: your-email@example.com # Replace with your email
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-prod-account-key
#     solvers:
#       - http01:
#           ingress:
#             class: nginx
