---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 77.6.2
  interval: 5m
  releaseName: prometheus
  values:
    prometheus:
      enabled: true
      prometheusSpec:
        scrapeConfigSelector:
          matchLabels: null
        podMonitorSelector:
          matchLabels: null
        probeSelector:
          matchLabels: null
        serviceMonitorSelector:
          matchLabels: null
        ruleSelector:
          matchLabels: null
    ## Disabled functionalities
    crds:
      enabled: true
    grafana:
      enabled: true
    alertmanager:
      enabled: false
    defaultRules:
      create: true
      rules:
        # These components are not deployed in the hcp cluster
        alertmanager: false
        kubeProxy: false
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
